name: Build

on:
  push:
    branches:
      - master
      - react_base
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install, Test and Build
        run: |
          yarn install
          yarn test
          yarn build